<?php

namespace CULabs\IlluminateBundle\Entity\Queue;

/**
 * FailedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FailedRepository extends \Doctrine\ORM\EntityRepository
{
}
